// Package storage provides tests for backup operations.
package storage

import (
	"os"
	"strings"
	"testing"

	"github.com/e6qu/dyscount/internal/models"
)

func TestTableManager_CreateBackup(t *testing.T) {
	// Create temporary directory for test databases
	tempDir, err := os.MkdirTemp("", "dyscount-backup-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tempDir)

	tm, err := NewTableManager(tempDir, "default")
	if err != nil {
		t.Fatalf("Failed to create table manager: %v", err)
	}

	// Create test table
	req := &models.DynamoDBRequest{
		TableName: "TestTable",
		KeySchema: []models.KeySchemaElement{
			{AttributeName: "pk", KeyType: "HASH"},
		},
		AttributeDefinitions: []models.AttributeDefinition{
			{AttributeName: "pk", AttributeType: "S"},
		},
	}

	_, err = tm.CreateTable(req)
	if err != nil {
		t.Fatalf("Failed to create table: %v", err)
	}

	// Create backup
	backupReq := &models.CreateBackupRequest{
		TableName:  "TestTable",
		BackupName: "TestBackup",
	}

	backup, err := tm.CreateBackup(backupReq)
	if err != nil {
		t.Fatalf("Failed to create backup: %v", err)
	}

	// Verify backup
	if backup.BackupName != "TestBackup" {
		t.Errorf("Expected BackupName=TestBackup, got %s", backup.BackupName)
	}
	if backup.TableName != "TestTable" {
		t.Errorf("Expected TableName=TestTable, got %s", backup.TableName)
	}
	if backup.BackupStatus != "AVAILABLE" {
		t.Errorf("Expected BackupStatus=AVAILABLE, got %s", backup.BackupStatus)
	}
	if backup.BackupArn == "" {
		t.Error("BackupArn should not be empty")
	}
	if backup.BackupSizeBytes == 0 {
		t.Error("BackupSizeBytes should not be 0")
	}
}

func TestTableManager_CreateBackup_AutoGeneratedName(t *testing.T) {
	// Create temporary directory for test databases
	tempDir, err := os.MkdirTemp("", "dyscount-backup-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tempDir)

	tm, err := NewTableManager(tempDir, "default")
	if err != nil {
		t.Fatalf("Failed to create table manager: %v", err)
	}

	// Create test table
	req := &models.DynamoDBRequest{
		TableName: "TestTable",
		KeySchema: []models.KeySchemaElement{
			{AttributeName: "pk", KeyType: "HASH"},
		},
		AttributeDefinitions: []models.AttributeDefinition{
			{AttributeName: "pk", AttributeType: "S"},
		},
	}

	_, err = tm.CreateTable(req)
	if err != nil {
		t.Fatalf("Failed to create table: %v", err)
	}

	// Create backup without specifying name
	backupReq := &models.CreateBackupRequest{
		TableName: "TestTable",
		// BackupName is empty
	}

	backup, err := tm.CreateBackup(backupReq)
	if err != nil {
		t.Fatalf("Failed to create backup: %v", err)
	}

	// Verify backup has auto-generated name
	if backup.BackupName == "" {
		t.Error("Expected auto-generated BackupName, got empty string")
	}
	if !strings.HasPrefix(backup.BackupName, "TestTable_backup_") {
		t.Errorf("Expected auto-generated name to start with 'TestTable_backup_', got %s", backup.BackupName)
	}
}

func TestTableManager_CreateBackup_NonExistentTable(t *testing.T) {
	// Create temporary directory for test databases
	tempDir, err := os.MkdirTemp("", "dyscount-backup-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tempDir)

	tm, err := NewTableManager(tempDir, "default")
	if err != nil {
		t.Fatalf("Failed to create table manager: %v", err)
	}

	// Try to create backup of non-existent table
	backupReq := &models.CreateBackupRequest{
		TableName:  "NonExistentTable",
		BackupName: "TestBackup",
	}

	_, err = tm.CreateBackup(backupReq)
	if err == nil {
		t.Error("Expected error when creating backup of non-existent table")
	}
}

func TestTableManager_ListBackups(t *testing.T) {
	// Create temporary directory for test databases
	tempDir, err := os.MkdirTemp("", "dyscount-backup-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tempDir)

	tm, err := NewTableManager(tempDir, "default")
	if err != nil {
		t.Fatalf("Failed to create table manager: %v", err)
	}

	// Create test table
	req := &models.DynamoDBRequest{
		TableName: "TestTable",
		KeySchema: []models.KeySchemaElement{
			{AttributeName: "pk", KeyType: "HASH"},
		},
		AttributeDefinitions: []models.AttributeDefinition{
			{AttributeName: "pk", AttributeType: "S"},
		},
	}

	_, err = tm.CreateTable(req)
	if err != nil {
		t.Fatalf("Failed to create table: %v", err)
	}

	// Create multiple backups
	for i := 0; i < 3; i++ {
		backupReq := &models.CreateBackupRequest{
			TableName:  "TestTable",
			BackupName: "TestBackup" + string(rune('0'+i)),
		}
		_, err := tm.CreateBackup(backupReq)
		if err != nil {
			t.Fatalf("Failed to create backup %d: %v", i, err)
		}
	}

	// List all backups
	listReq := &models.ListBackupsRequest{}
	backups, err := tm.ListBackups(listReq)
	if err != nil {
		t.Fatalf("Failed to list backups: %v", err)
	}

	if len(backups) != 3 {
		t.Errorf("Expected 3 backups, got %d", len(backups))
	}

	// List with limit
	listReq = &models.ListBackupsRequest{Limit: 2}
	backups, err = tm.ListBackups(listReq)
	if err != nil {
		t.Fatalf("Failed to list backups: %v", err)
	}

	if len(backups) != 2 {
		t.Errorf("Expected 2 backups with limit, got %d", len(backups))
	}
}

func TestTableManager_DeleteBackup(t *testing.T) {
	// Create temporary directory for test databases
	tempDir, err := os.MkdirTemp("", "dyscount-backup-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tempDir)

	tm, err := NewTableManager(tempDir, "default")
	if err != nil {
		t.Fatalf("Failed to create table manager: %v", err)
	}

	// Create test table
	req := &models.DynamoDBRequest{
		TableName: "TestTable",
		KeySchema: []models.KeySchemaElement{
			{AttributeName: "pk", KeyType: "HASH"},
		},
		AttributeDefinitions: []models.AttributeDefinition{
			{AttributeName: "pk", AttributeType: "S"},
		},
	}

	_, err = tm.CreateTable(req)
	if err != nil {
		t.Fatalf("Failed to create table: %v", err)
	}

	// Create backup
	backupReq := &models.CreateBackupRequest{
		TableName:  "TestTable",
		BackupName: "ToDelete",
	}

	backup, err := tm.CreateBackup(backupReq)
	if err != nil {
		t.Fatalf("Failed to create backup: %v", err)
	}

	// Verify backup exists
	listReq := &models.ListBackupsRequest{}
	backups, _ := tm.ListBackups(listReq)
	if len(backups) != 1 {
		t.Fatalf("Expected 1 backup before deletion, got %d", len(backups))
	}

	// Delete backup
	deleted, err := tm.DeleteBackup(backup.BackupArn)
	if err != nil {
		t.Fatalf("Failed to delete backup: %v", err)
	}

	if deleted.BackupStatus != "DELETED" {
		t.Errorf("Expected BackupStatus=DELETED, got %s", deleted.BackupStatus)
	}

	// Verify backup is gone
	backups, _ = tm.ListBackups(listReq)
	if len(backups) != 0 {
		t.Errorf("Expected 0 backups after deletion, got %d", len(backups))
	}
}

func TestTableManager_DeleteBackup_NonExistent(t *testing.T) {
	// Create temporary directory for test databases
	tempDir, err := os.MkdirTemp("", "dyscount-backup-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tempDir)

	tm, err := NewTableManager(tempDir, "default")
	if err != nil {
		t.Fatalf("Failed to create table manager: %v", err)
	}

	// Try to delete non-existent backup
	_, err = tm.DeleteBackup("arn:aws:dynamodb:local:000000000000:table/TestTable/backup/NonExistent")
	if err == nil {
		t.Error("Expected error when deleting non-existent backup")
	}
}

func TestTableManager_RestoreTableFromBackup(t *testing.T) {
	// Create temporary directory for test databases
	tempDir, err := os.MkdirTemp("", "dyscount-backup-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tempDir)

	tm, err := NewTableManager(tempDir, "default")
	if err != nil {
		t.Fatalf("Failed to create table manager: %v", err)
	}

	// Create test table
	req := &models.DynamoDBRequest{
		TableName: "SourceTable",
		KeySchema: []models.KeySchemaElement{
			{AttributeName: "pk", KeyType: "HASH"},
		},
		AttributeDefinitions: []models.AttributeDefinition{
			{AttributeName: "pk", AttributeType: "S"},
		},
	}

	_, err = tm.CreateTable(req)
	if err != nil {
		t.Fatalf("Failed to create table: %v", err)
	}

	// Create backup
	backupReq := &models.CreateBackupRequest{
		TableName:  "SourceTable",
		BackupName: "SourceBackup",
	}

	backup, err := tm.CreateBackup(backupReq)
	if err != nil {
		t.Fatalf("Failed to create backup: %v", err)
	}

	// Restore table from backup
	restoreReq := &models.RestoreTableFromBackupRequest{
		BackupArn:       backup.BackupArn,
		TargetTableName: "RestoredTable",
	}

	metadata, err := tm.RestoreTableFromBackup(restoreReq)
	if err != nil {
		t.Fatalf("Failed to restore table: %v", err)
	}

	// Verify restored table
	if metadata.TableName != "RestoredTable" {
		t.Errorf("Expected TableName=RestoredTable, got %s", metadata.TableName)
	}

	// Verify table exists
	tables, _ := tm.ListTables()
	found := false
	for _, name := range tables {
		if name == "RestoredTable" {
			found = true
			break
		}
	}
	if !found {
		t.Error("Restored table not found in table list")
	}
}

func TestTableManager_RestoreTableFromBackup_TargetExists(t *testing.T) {
	// Create temporary directory for test databases
	tempDir, err := os.MkdirTemp("", "dyscount-backup-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tempDir)

	tm, err := NewTableManager(tempDir, "default")
	if err != nil {
		t.Fatalf("Failed to create table manager: %v", err)
	}

	// Create source table
	sourceReq := &models.DynamoDBRequest{
		TableName: "SourceTable",
		KeySchema: []models.KeySchemaElement{
			{AttributeName: "pk", KeyType: "HASH"},
		},
		AttributeDefinitions: []models.AttributeDefinition{
			{AttributeName: "pk", AttributeType: "S"},
		},
	}

	_, err = tm.CreateTable(sourceReq)
	if err != nil {
		t.Fatalf("Failed to create source table: %v", err)
	}

	// Create target table (that already exists)
	targetReq := &models.DynamoDBRequest{
		TableName: "TargetTable",
		KeySchema: []models.KeySchemaElement{
			{AttributeName: "pk", KeyType: "HASH"},
		},
		AttributeDefinitions: []models.AttributeDefinition{
			{AttributeName: "pk", AttributeType: "S"},
		},
	}

	_, err = tm.CreateTable(targetReq)
	if err != nil {
		t.Fatalf("Failed to create target table: %v", err)
	}

	// Create backup
	backupReq := &models.CreateBackupRequest{
		TableName:  "SourceTable",
		BackupName: "SourceBackup",
	}

	backup, err := tm.CreateBackup(backupReq)
	if err != nil {
		t.Fatalf("Failed to create backup: %v", err)
	}

	// Try to restore to existing table
	restoreReq := &models.RestoreTableFromBackupRequest{
		BackupArn:       backup.BackupArn,
		TargetTableName: "TargetTable",
	}

	_, err = tm.RestoreTableFromBackup(restoreReq)
	if err == nil {
		t.Error("Expected error when restoring to existing table")
	}
	if !strings.Contains(err.Error(), "already exists") {
		t.Errorf("Expected 'already exists' error, got: %v", err)
	}
}

func TestTableManager_RestoreTableFromBackup_NonExistentBackup(t *testing.T) {
	// Create temporary directory for test databases
	tempDir, err := os.MkdirTemp("", "dyscount-backup-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tempDir)

	tm, err := NewTableManager(tempDir, "default")
	if err != nil {
		t.Fatalf("Failed to create table manager: %v", err)
	}

	// Try to restore from non-existent backup
	restoreReq := &models.RestoreTableFromBackupRequest{
		BackupArn:       "arn:aws:dynamodb:local:000000000000:table/TestTable/backup/NonExistent",
		TargetTableName: "TargetTable",
	}

	_, err = tm.RestoreTableFromBackup(restoreReq)
	if err == nil {
		t.Error("Expected error when restoring from non-existent backup")
	}
}
